### ISSUE TITLE
Feature request: implement updater so that the app can update itself when it was installed from the APK on the github releases page

### ISSUE THREAD

**Issue by heapifyman** [gematik/E-Rezept-App-Android#21]
In #1 it was commented:

> Instead of releasing on F-Droid or other stores besides Google Play and Huawei AppGallery, we decided to publish the APK for each released version here on Gihub starting with the [1.2.1 release](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.2.1). We think this is a good solution.

Unfortunately, that means that users who cannot or do not want to use Google services have to manually check for and install any updates.

I think that an F-Droid release would still be the better option - @Gematik-Entwicklung could also setup their own F-Droid repository, like e.g. [Corona Contact Tracing Germany did](https://cctg.codeberg.page/).

But as long as there is no F-Droid release, an intermediate solution might be to implement an updater directly in the app. Several other apps like [Signal](https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/jobs/ApkUpdateJob.kt) already do that (I think Threema does it, too).

Auto-update should be opt-in for the user (= disabled by default)

**Comment by xandro0777** [comment]
Some users won't  trust apps that auto update themselves, so this should be optional and disabled by default. 

Anyway, why complicate the App with an updater if it can be released in F-Droid? Getting an updater to operate safely without introducing additional security risks requires a lot of effort which F-Droid already solved.

**Comment by xandro0777** [comment]
Hopefully Signal got it right, though I doubt they download their apk from Github. Perhaps they have a dedicated server for this where they can pin the https cetificate and IP. Can't do that witih github obviously, they may rotate their certificates anytime they want and the download request will be likely redirected to somewhere in some cdn.

Github is not designed for that and don't forget how many Github projects were compromised in one way or another in the past few years because of common configuration problems.

Of course Gematik could dedicate a special server but that would make things even less transparent.

Duplicating effort to solve a problem that has a better solution.
